/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication35;

import javax.swing.JOptionPane;

/**
 *
 * @author ailto
 */
public class TelaMain2 extends javax.swing.JFrame {

    /**
     * Creates new form TelaMain
     */
    public TelaMain2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastrarUsuarioButton = new javax.swing.JButton();
        exibirTodosUsuariosButton = new javax.swing.JButton();
        deletarUsuarioButton = new javax.swing.JButton();
        alterarUsuarioButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastrarUsuarioButton.setText("Cadastrar Usuario");
        cadastrarUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarUsuarioButtonActionPerformed(evt);
            }
        });

        exibirTodosUsuariosButton.setText("Exibir Todos Usuarios");

        deletarUsuarioButton.setText("Deletar Usuario");
        deletarUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarUsuarioButtonActionPerformed(evt);
            }
        });

        alterarUsuarioButton.setText(" Alterar Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alterarUsuarioButton)
                    .addComponent(deletarUsuarioButton)
                    .addComponent(cadastrarUsuarioButton)
                    .addComponent(exibirTodosUsuariosButton))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(cadastrarUsuarioButton)
                .addGap(55, 55, 55)
                .addComponent(exibirTodosUsuariosButton)
                .addGap(51, 51, 51)
                .addComponent(deletarUsuarioButton)
                .addGap(48, 48, 48)
                .addComponent(alterarUsuarioButton)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deletarUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarUsuarioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletarUsuarioButtonActionPerformed

    private void cadastrarUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarUsuarioButtonActionPerformed
        // TODO add your handling code here:
         String nome = JOptionPane.showInputDialog("Digite seu nome: ");
        String email = JOptionPane.showInputDialog("Digite seu email: ");
        String senha = JOptionPane.showInputDialog("Digite sua senha: ");
        String altura = JOptionPane.showInputDialog("Digite sua altura em metros: ");
        int idade = Integer.parseInt(JOptionPane.showInputDialog("Digite sua idade em anos: "));
        String peso = JOptionPane.showInputDialog("Digite seu peso em quilos: ");
        int frequencia = Integer.parseInt(JOptionPane.showInputDialog("Digite sua frequencia semanal de exercicios (0 a 7): "));
        String genero =  JOptionPane.showInputDialog("Digite seu genero (M ou F): ");
        boolean admin = false;

        
    
       
            
        // Handle the SQL exception as needed
    
    }//GEN-LAST:event_cadastrarUsuarioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMain2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMain2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMain2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMain2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMain2().setVisible(true);
            }
                                                          
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarUsuarioButton;
    private javax.swing.JButton cadastrarUsuarioButton;
    private javax.swing.JButton deletarUsuarioButton;
    private javax.swing.JButton exibirTodosUsuariosButton;
    // End of variables declaration//GEN-END:variables
}
